development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: codesaurus_dev
  socket: /Applications/MAMP/tmp/mysql/mysql.sock
  pool: 5
  username: root
  password: root
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: codesaurus_test
  socket: /Applications/MAMP/tmp/mysql/mysql.sock
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: codesaurus_prod
  socket: /Applications/MAMP/tmp/mysql/mysql.sock
  pool: 5
  username: root
  password: root
  host: localhost
